name: puzzle
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  animated_widgets: ^1.1.0
  audioplayers: null
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  loggy: ^2.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/click.mp3
    - assets/reset.mp3
    - assets/dumuraLogo.png
